### PR TITLE
build: replace version number with latest tag

### PR DESCRIPTION
**Pull request by setchy**
I can't see a strong need at this time for us to keep the website version in-sync with the gitify release version.  

Suggesting we update to use a static `latest` tag

### CODE REVIEW

**Comment by setchy** [comment]
> But since astro generates a static output out of the version, doesn't it not work long term (at least the fetching of the latest version)

Good callout.  I guess the important part is that the website is "redeployed" when a new version is released, or, can we make the version number dynamically fetched

I noticed that before the release last night, the package.json had version 5.5.0, but gitify.io was showing 5.6.0 due to us merging Renovate PRs in this repo...

**Comment by bmulholland** [comment]
Is there an easy way to trigger a website rebuild? Could just add that to the release script

**Comment by afonsojramos** [comment]
There's 3 options here:
1.We rebuild on every release
2. We remove the version from the website and there's no need to load anything that changes and it is just latest all year round
3. We make it a dynamic component that checks for the latest version on the client

I'm leaning towards 2 to be honest.

**Comment by setchy** [comment]
I like option 2 also, but I don't think we'll be able to find a URL that points to the latest release with version named attached artifacts :)

**Comment by setchy** [comment]
Option 4 - we find a fix for the workflow that keeps failing 😅 haha

**Comment by bmulholland** [comment]
I agree with option 2 -- I don't think an actual version number on the website adds value to anything.

**Comment by setchy** [comment]
Option 5 - trigger the netlify deployment based on tag events - https://github.com/gitify-app/gitify/pull/1199

**Review by afonsojramos — APPROVED** [review]
I guess that this doesn't hurt now :)

**Pull request merged**
